[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "$PORT"

[nixpacks]
# 👇 Force the Node.js version to v22.12.0
phases.build.nixPkgs = ["nodejs_22"]
